"use client"

import { ExportModal } from "./ExportModal"
import { isInspectorInputDragActive } from "./InspectorControlModel"
import { AppTopBar } from "./AppTopBar"
import { ViewportStage } from "./ViewportStage"
import { TimelineDock } from "./TimelineDock"
import { useLightEditor } from "./useLightEditor"
import { useMaterialEditor } from "./useMaterialEditor"
import { InspectorSidebar } from "./InspectorSidebar"
import { useFillEditor } from "./useFillEditor"
import { useThemeControls } from "./useThemeControls"
import { useShapeSequenceEditor } from "./useShapeSequenceEditor"
import { useGeometryEditor } from "./useGeometryEditor"
import { useViewportOptions } from "./useViewportOptions"
import { useTransformEditor } from "./useTransformEditor"
import { useTimelineTracks } from "./useTimelineTracks"
import { useEditorPlaybackState } from "./useEditorPlaybackState"
import { useEditorSelectionNavigation } from "./useEditorSelectionNavigation"
import { useEditorTimelineSurface } from "./useEditorTimelineSurface"
import { useEditorViewportSurface } from "./useEditorViewportSurface"
import { useEditorExportSurface } from "./useEditorExportSurface"
import { useEditorInspectorSurface } from "./useEditorInspectorSurface"
import { useEditorHistorySurface } from "./useEditorHistorySurface"
import { useEditorRenderState } from "./useEditorRenderState"
import { useEditorMotionSurface } from "./useEditorMotionSurface"
import { useEditorRecipeSurface } from "./useEditorRecipeSurface"

export default function AppLayout() {
  const { themeMounted, isLightTheme, themeToggleLabel, setTheme } =
    useThemeControls()

  const {
    canvas3DRef,
    duration,
    setDuration,
    currentTime,
    setCurrentTime,
    isPlaying,
    setIsPlaying,
    loop,
    setLoop,
    isPreviewModelReady,
    setIsPreviewModelReady,
    exportTimelineVideo,
    stopPlayback,
    togglePlayback: handlePlayToggle,
    resetPlayback: handleReset,
    animatedSeekEnabled,
    setAnimatedSeekEnabled,
    cancelAnimatedSeek,
    seekToTime,
  } = useEditorPlaybackState()

  const {
    shapes,
    setShapes,
    selectedShapeId,
    setSelectedShapeId,
    openShapePicker,
    setOpenShapePicker,
    activeRecipeId,
    setActiveRecipeId,
    markCustom,
    setShapeIcon,
    setShapeWipePair,
    addShapeAtPlayhead,
    removeShape,
  } = useShapeSequenceEditor({ currentTime, duration })

  const {
    wireframe,
    extrusionDepth,
    setExtrusionDepth,
    bevelEnabled,
    setBevelEnabled,
    bevelThickness,
    setBevelThickness,
    bevelSize,
    setBevelSize,
    bevelSegments,
    setBevelSegments,
    geometryQuality,
    setGeometryQuality,
    qualityKeyframes,
    setQualityKeyframes,
    layerSpacing,
    setLayerSpacing,
    innerElementScale,
    setInnerElementScale,
    innerScaleKeyframes,
    setInnerScaleKeyframes,
  } = useGeometryEditor()
  const {
    objectScale,
    setObjectScale,
    objectScaleAxes,
    setObjectScaleAxes,
    moveOffset,
    setMoveOffset,
    moveKeyframes,
    setMoveKeyframes,
    rotationOffset,
    setRotationOffset,
    rotationAxisKeyframes,
    setRotationAxisKeyframes,
    previewRotationY,
    setPreviewRotationY,
    isScaleLocked,
    setIsScaleLocked,
  } = useTransformEditor()

  const {
    enableGradient,
    fillMode,
    fillColor,
    fillColorSecondary,
    fillGradientType,
    fillStops,
    fillKeyframes,
    setFillKeyframes,
    restoreFillState,
    applyRecipeFill,
    setGradientEnabled,
    updateFillColor,
    updateGradientType,
    updateFillStops,
  } = useFillEditor({
    currentTime,
    duration,
    onEdit: markCustom,
  })
  const {
    zoom,
    setZoom,
    viewInertiaEnabled,
    setViewInertiaEnabled,
    showCenterPoint,
    setShowCenterPoint,
    showTransformGizmo,
    setShowTransformGizmo,
    zenMode,
    setZenMode,
    isDragging,
    setIsDragging,
  } = useViewportOptions()

  const {
    materialPreset,
    setMaterialPreset,
    roughness,
    metalness,
    reflectance,
    clearcoat,
    clearcoatRoughness,
    transmission,
    thickness,
    emissiveIntensity,
    materialKeyframes,
    setMaterialKeyframes,
    isAdvancedMaterialOpen,
    setIsAdvancedMaterialOpen,
    activeMaterialSettings,
    setMaterialBaseSettings,
    updateMaterialSetting,
    applyMaterialPreset,
  } = useMaterialEditor({
    currentTime,
    duration,
    onEdit: markCustom,
  })
  const {
    ambientColor,
    ambientIntensity,
    keyLightColor,
    setKeyLightColor,
    keyLightIntensity,
    setKeyLightIntensity,
    keyLightPosition,
    setKeyLightPosition,
    keyLightSoftness,
    setKeyLightSoftness,
    keyLightPositionKeyframes,
    setKeyLightPositionKeyframes,
    activeKeyLightPosition,
    lightPositionKeyframeAtPlayhead,
    toggleLightPositionKeyframeAtPlayhead,
    updateLightPositionXY,
    rimLightColor,
    rimLightIntensity,
  } = useLightEditor({
    currentTime,
    duration,
    onEdit: markCustom,
  })
  const {
    inspectorRefs,
    selectedMotionTrackId,
    setSelectedMotionTrackId,
    selectTimelineTrack,
    selectTimelinePropertyRow,
  } = useEditorSelectionNavigation({
    setAdvancedMaterialOpen: setIsAdvancedMaterialOpen,
    setSelectedShapeId,
  })

  const { tracks, setTracks, extrusionTrack, scaleTrack, lightingTrack } =
    useTimelineTracks()

  useEditorRecipeSurface({
    duration,
    setActiveRecipeId,
    setMaterialPreset,
    applyRecipeFill,
    setShapes,
    setSelectedShapeId,
    setMaterialBaseSettings,
    setExtrusionDepth,
    setBevelEnabled,
    setBevelThickness,
    setBevelSize,
    setBevelSegments,
    setGeometryQuality,
    setLayerSpacing,
    setInnerElementScale,
    setRotationOffset,
    setRotationAxisKeyframes,
    setObjectScale,
    setMoveOffset,
    setMoveKeyframes,
    setQualityKeyframes,
    setInnerScaleKeyframes,
    setKeyLightIntensity,
    setKeyLightPosition,
    setKeyLightSoftness,
    setKeyLightPositionKeyframes,
    setTracks,
    setSelectedMotionTrackId,
    setCurrentTime,
    setIsPlaying,
  })

  useEditorHistorySurface({
    activeRecipeId,
    setActiveRecipeId,
    shapes,
    setShapes,
    setSelectedShapeId,
    setOpenShapePicker,
    duration,
    setDuration,
    setCurrentTime,
    materialPreset,
    setMaterialPreset,
    roughness,
    metalness,
    reflectance,
    clearcoat,
    clearcoatRoughness,
    transmission,
    thickness,
    emissiveIntensity,
    materialKeyframes,
    setMaterialKeyframes,
    setMaterialBaseSettings,
    extrusionDepth,
    setExtrusionDepth,
    bevelEnabled,
    setBevelEnabled,
    bevelThickness,
    setBevelThickness,
    bevelSize,
    setBevelSize,
    bevelSegments,
    setBevelSegments,
    geometryQuality,
    setGeometryQuality,
    qualityKeyframes,
    setQualityKeyframes,
    layerSpacing,
    setLayerSpacing,
    innerElementScale,
    setInnerElementScale,
    innerScaleKeyframes,
    setInnerScaleKeyframes,
    objectScale,
    setObjectScale,
    objectScaleAxes,
    setObjectScaleAxes,
    moveOffset,
    setMoveOffset,
    moveKeyframes,
    setMoveKeyframes,
    enableGradient,
    fillMode,
    fillColor,
    fillColorSecondary,
    fillGradientType,
    fillStops,
    fillKeyframes,
    restoreFillState,
    rotationOffset,
    setRotationOffset,
    rotationAxisKeyframes,
    setRotationAxisKeyframes,
    setPreviewRotationY,
    keyLightColor,
    setKeyLightColor,
    keyLightIntensity,
    setKeyLightIntensity,
    keyLightPosition,
    setKeyLightPosition,
    keyLightSoftness,
    setKeyLightSoftness,
    keyLightPositionKeyframes,
    setKeyLightPositionKeyframes,
    tracks,
    setTracks,
    setIsPlaying,
    isInputDragActive: isInspectorInputDragActive,
    onPlayPause: handlePlayToggle,
  })

  const {
    sortedShapes,
    morph,
    selectedShapeFill,
    selectedShapeFillSecondary,
    selectedShapeGradientType,
    selectedShapeFillStops,
    iconAContent,
    iconBContent,
    colorA,
    renderColorASecondary,
    renderColorAStops,
    renderColorB,
    renderColorBSecondary,
    renderColorBStops,
    activeTransitionProgress,
    transitionType,
    wipeDirection,
    renderEnableGradient,
    renderGradientType,
    selectedShapeLayers,
    selectedLayer,
    selectedLayerId,
    selectedLayerOverride,
    setSelectedLayerId,
    updateSelectedLayerScale,
    updateSelectedLayerDepth,
    toggleSelectedLayerVisibility,
    shapeNavigation,
    activeExtrusionDepth,
    activeRotationOffset,
    activeObjectScale,
    activeMoveOffset,
    activeKeyLightIntensity,
    activeGeometryQuality,
    activeInnerScale,
  } = useEditorRenderState({
    shapes,
    setShapes,
    selectedShapeId,
    setSelectedShapeId,
    currentTime,
    fillColor,
    fillColorSecondary,
    fillGradientType,
    fillStops,
    fillKeyframes,
    fillMode,
    enableGradient,
    extrusionTrack,
    scaleTrack,
    lightingTrack,
    extrusionDepth,
    rotationOffset,
    rotationAxisKeyframes,
    previewRotationY,
    objectScale,
    moveOffset,
    moveKeyframes,
    keyLightIntensity,
    geometryQuality,
    qualityKeyframes,
    innerElementScale,
    innerScaleKeyframes,
    markCustom,
  })

  const {
    handleDepthChange,
    handleRotationAxisChange,
    handleScaleChange,
    handleScaleAxisChange,
    handleViewRotationCommit,
    handleViewRotationSet,
    handleBrightnessChange,
    updateMoveAxis,
    updateQuality,
    resetView,
  } = useEditorMotionSurface({
    currentTime,
    duration,
    tracks,
    setTracks,
    setSelectedMotionTrackId,
    setActiveRecipeId,
    setExtrusionDepth,
    setRotationOffset,
    activeRotationOffset,
    setRotationAxisKeyframes,
    setPreviewRotationY,
    setObjectScale,
    setObjectScaleAxes,
    setIsScaleLocked,
    activeMoveOffset,
    setMoveOffset,
    setMoveKeyframes,
    setKeyLightIntensity,
    setGeometryQuality,
    setQualityKeyframes,
    geometryQuality,
    canvas3DRef,
  })

  const {
    openExport,
    uploadFileRef,
    handleUploadInputChange,
    handleDropSvg,
    triggerShapeUpload,
    exportModalProps,
  } = useEditorExportSurface({
    selectedShapeId,
    setShapes,
    canvasRef: canvas3DRef,
    exportTimelineVideo,
    materialPreset,
    colorA,
    colorB: renderColorB,
    roughness,
    metalness,
    reflectance,
    clearcoat,
    clearcoatRoughness,
    transmission,
    thickness,
    emissiveIntensity,
    extrusionDepth: activeExtrusionDepth,
    bevelEnabled,
    bevelThickness,
    bevelSize,
    bevelSegments,
    layerSpacing,
    ambientIntensity,
    keyLightIntensity: activeKeyLightIntensity,
    rimLightIntensity,
    svgPathA: iconAContent,
    svgPathB: iconBContent,
    markCustom,
  })

  const {
    timelineProps,
    previousBreakpoint,
    nextBreakpoint,
    atTimelineStart,
    atTimelineEnd,
    playbackProgress,
    goToPreviousBreakpoint,
    goToNextBreakpoint,
    goToEnd,
  } = useEditorTimelineSurface({
    currentTime,
    setCurrentTime,
    duration,
    setDuration,
    seekToTime,
    cancelAnimatedSeek,
    stopPlayback,
    isPlaying,
    isPreviewModelReady,
    loop,
    setLoop,
    tracks,
    setTracks,
    sortedShapes,
    shapes,
    setShapes,
    selectedShapeId,
    setSelectedShapeId,
    openShapePicker,
    setOpenShapePicker,
    selectedMotionTrackId,
    selectTimelineTrack,
    selectTimelinePropertyRow,
    fillKeyframes,
    setFillKeyframes,
    materialKeyframes,
    setMaterialKeyframes,
    keyLightPositionKeyframes,
    setKeyLightPositionKeyframes,
    rotationAxisKeyframes,
    setRotationAxisKeyframes,
    moveKeyframes,
    setMoveKeyframes,
    setQualityKeyframes,
    selectedShapeFillStops,
    selectedShapeGradientType,
    activeMaterialSettings,
    activeKeyLightPosition,
    activeRotationOffset,
    activeMoveOffset,
    setShapeIcon,
    setShapeWipePair,
    addShapeAtPlayhead,
    removeShape,
    triggerShapeUpload,
    markCustom,
  })
  const { canvasProps, viewOptionsProps, playbackProps } =
    useEditorViewportSurface({
      iconAContent,
      iconBContent,
      materialPreset,
      colorA,
      colorB: renderColorB,
      colorASecondary: renderColorASecondary,
      colorBSecondary: renderColorBSecondary,
      colorAStops: renderColorAStops,
      colorBStops: renderColorBStops,
      enableGradient: renderEnableGradient,
      gradientType: renderGradientType,
      activeMaterialSettings,
      wireframe,
      extrusionDepth: activeExtrusionDepth,
      bevelEnabled,
      bevelThickness,
      bevelSize,
      bevelSegments,
      geometryQuality: activeGeometryQuality,
      layerSpacing,
      innerElementScale: activeInnerScale,
      transitionType,
      wipeDirection,
      transitionProgress: activeTransitionProgress,
      rotationOffset: activeRotationOffset,
      objectScale: activeObjectScale,
      objectScaleAxes,
      moveOffset: activeMoveOffset,
      isPlaying,
      ambientColor,
      ambientIntensity,
      keyLightColor,
      keyLightIntensity: activeKeyLightIntensity,
      keyLightPosition: activeKeyLightPosition,
      keyLightSoftness,
      rimLightColor,
      rimLightIntensity,
      zoom,
      viewInertiaEnabled,
      showCenterPoint,
      showTransformGizmo,
      selectedLayerId,
      pathOverridesA: morph.from.pathOverrides,
      pathOverridesB: morph.to.pathOverrides,
      playbackProgress,
      atTimelineStart,
      atTimelineEnd,
      hasPreviousBreakpoint: previousBreakpoint !== undefined,
      hasNextBreakpoint: nextBreakpoint !== undefined,
      zenMode,
      animatedSeekEnabled,
      setZoom,
      handleViewRotationCommit,
      handleViewRotationSet,
      handleScaleChange,
      handleScaleAxisChange,
      updateMoveAxis,
      handleRotationAxisChange,
      setIsPreviewModelReady,
      resetView,
      setViewInertiaEnabled,
      setShowCenterPoint,
      setShowTransformGizmo,
      setAnimatedSeekEnabled,
      handleReset,
      goToPreviousBreakpoint,
      handlePlayToggle,
      goToNextBreakpoint,
      goToEnd,
      setZenMode,
      markCustom,
    })
  const { styleProps, geometryProps, transformProps, lightProps } =
    useEditorInspectorSurface({
      currentTime,
      duration,
      setTracks,
      setSelectedMotionTrackId,
      setActiveRecipeId,
      fillKeyframes,
      setFillKeyframes,
      materialKeyframes,
      setMaterialKeyframes,
      selectedShapeFillStops,
      selectedShapeGradientType,
      activeMaterialSettings,
      scaleTrack,
      activeObjectScale,
      activeRotationOffset,
      rotationAxisKeyframes,
      setRotationAxisKeyframes,
      activeMoveOffset,
      moveKeyframes,
      setMoveKeyframes,
      keyLightPositionKeyframes,
      lightPositionKeyframeAtPlayhead,
      toggleLightPositionKeyframeAtPlayhead,
      markCustom,
      stopPlayback,
      setCurrentTime,
      fillRef: inspectorRefs.fill,
      materialRef: inspectorRefs.material,
      materialPreset,
      materialKeyframeCount: materialKeyframes.length,
      isAdvancedMaterialOpen,
      selectedShapeFill,
      selectedShapeFillSecondary,
      fillMode,
      onFillColorChange: updateFillColor,
      onGradientToggle: setGradientEnabled,
      onGradientTypeChange: updateGradientType,
      onStopsChange: updateFillStops,
      onMaterialPresetChange: applyMaterialPreset,
      onAdvancedMaterialOpenChange: setIsAdvancedMaterialOpen,
      onMaterialSettingChange: updateMaterialSetting,
      extrusionRef: inspectorRefs.extrusion,
      selectedMotionTrackId,
      extrusionTrack,
      activeExtrusionDepth,
      extrusionDepth,
      activeGeometryQuality,
      bevelEnabled,
      bevelSegments,
      onDepthChange: handleDepthChange,
      onBevelEnabledChange: setBevelEnabled,
      onBevelSegmentsChange: setBevelSegments,
      onQualityChange: updateQuality,
      onCustomEdit: markCustom,
      scaleRef: inspectorRefs.scale,
      rotationRef: inspectorRefs.rotation,
      moveRef: inspectorRefs.move,
      objectScale,
      objectScaleAxes,
      isScaleLocked,
      rotationOffset: activeRotationOffset,
      moveKeyframesLength: moveKeyframes.length,
      selectedShapeLayers,
      selectedLayer,
      selectedLayerId,
      selectedLayerOverride,
      shapeNavigation,
      onScaleLockChange: setIsScaleLocked,
      onScaleChange: handleScaleChange,
      onScaleAxisChange: handleScaleAxisChange,
      onRotationAxisChange: handleRotationAxisChange,
      onMoveAxisChange: updateMoveAxis,
      onSelectLayer: setSelectedLayerId,
      onToggleLayerVisibility: toggleSelectedLayerVisibility,
      onLayerScaleChange: updateSelectedLayerScale,
      onLayerDepthChange: updateSelectedLayerDepth,
      lightingRef: inspectorRefs.lighting,
      lightingTrack,
      activeKeyLightIntensity,
      keyLightIntensity,
      activeKeyLightPosition,
      keyLightColor,
      keyLightSoftness,
      lightPositionIsKeyed: Boolean(lightPositionKeyframeAtPlayhead()),
      onLightPositionChange: updateLightPositionXY,
      onLightColorChange: setKeyLightColor,
      onLightSoftnessChange: setKeyLightSoftness,
      onToggleLightPositionKeyframe: toggleLightPositionKeyframeAtPlayhead,
      onBrightnessChange: handleBrightnessChange,
    })

  return (
    <div className="flex h-screen w-screen flex-col overflow-hidden bg-background font-sans text-foreground antialiased select-none">
      <AppTopBar
        zenMode={zenMode}
        themeMounted={themeMounted}
        isLightTheme={isLightTheme}
        themeToggleLabel={themeToggleLabel}
        onZenModeChange={setZenMode}
        onThemeChange={setTheme}
        onExportOpen={openExport}
      />

      <div className="flex min-h-0 flex-1 bg-muted/40">
        <ViewportStage
          ref={canvas3DRef}
          zenMode={zenMode}
          isDragging={isDragging}
          onDragStateChange={setIsDragging}
          onDropSvg={handleDropSvg}
          canvasProps={canvasProps}
          viewOptionsProps={viewOptionsProps}
          playbackProps={playbackProps}
        />

        <InspectorSidebar
          zenMode={zenMode}
          styleProps={styleProps}
          geometryProps={geometryProps}
          transformProps={transformProps}
          lightProps={lightProps}
        />
      </div>

      <TimelineDock zenMode={zenMode} timelineProps={timelineProps} />

      <input
        ref={uploadFileRef}
        type="file"
        accept=".svg"
        className="hidden"
        onChange={handleUploadInputChange}
      />

      {/* =========================================================================
          4. EXPORT STUDIO MODAL
          ========================================================================= */}
      <ExportModal {...exportModalProps} />
    </div>
  )
}
