"use client"

import { useEditorBaseState } from "./useEditorBaseState"
import { useEditorDocumentLifecycle } from "./useEditorDocumentLifecycle"
import { useEditorTimelineSurface } from "./useEditorTimelineSurface"
import { useEditorViewportSurface } from "./useEditorViewportSurface"
import { useEditorExportSurface } from "./useEditorExportSurface"
import { useEditorInspectorSurface } from "./useEditorInspectorSurface"
import { useEditorRenderState } from "./useEditorRenderState"
import { useEditorMotionSurface } from "./useEditorMotionSurface"
import type { AppLayoutViewProps } from "./AppLayoutView"

export function useAppLayoutController(): AppLayoutViewProps {
  const editor = useEditorBaseState()
  useEditorDocumentLifecycle(editor)

  const {
    theme: { themeMounted, isLightTheme, themeToggleLabel, setTheme },
    playback: {
      canvas3DRef,
      duration,
      setDuration,
      currentTime,
      setCurrentTime,
      isPlaying,
      loop,
      setLoop,
      isPreviewModelReady,
      setIsPreviewModelReady,
      exportTimelineVideo,
      stopPlayback,
      togglePlayback: handlePlayToggle,
      resetPlayback: handleReset,
      animatedSeekEnabled,
      setAnimatedSeekEnabled,
      cancelAnimatedSeek,
      seekToTime,
    },
    shapes: {
      shapes,
      setShapes,
      selectedShapeId,
      setSelectedShapeId,
      openShapePicker,
      setOpenShapePicker,
      setActiveRecipeId,
      markCustom,
      setShapeIcon,
      setShapeWipePair,
      addShapeAtPlayhead,
      removeShape,
    },
    geometry: {
      wireframe,
      extrusionDepth,
      setExtrusionDepth,
      bevelEnabled,
      setBevelEnabled,
      bevelThickness,
      bevelSize,
      bevelSegments,
      setBevelSegments,
      geometryQuality,
      setGeometryQuality,
      qualityKeyframes,
      setQualityKeyframes,
      layerSpacing,
      innerElementScale,
      innerScaleKeyframes,
      setInnerScaleKeyframes,
    },
    transform: {
      objectScale,
      setObjectScale,
      objectScaleAxes,
      setObjectScaleAxes,
      moveOffset,
      setMoveOffset,
      moveKeyframes,
      setMoveKeyframes,
      rotationOffset,
      setRotationOffset,
      rotationAxisKeyframes,
      setRotationAxisKeyframes,
      previewRotationY,
      setPreviewRotationY,
      isScaleLocked,
      setIsScaleLocked,
    },
    fill: {
      enableGradient,
      fillMode,
      fillColor,
      fillColorSecondary,
      fillGradientType,
      fillStops,
      fillKeyframes,
      setFillKeyframes,
      setGradientEnabled,
      updateFillColor,
      updateGradientType,
      updateFillStops,
    },
    viewport: {
      zoom,
      setZoom,
      viewInertiaEnabled,
      setViewInertiaEnabled,
      showCenterPoint,
      setShowCenterPoint,
      showTransformGizmo,
      setShowTransformGizmo,
      zenMode,
      setZenMode,
      isDragging,
      setIsDragging,
    },
    material: {
      materialPreset,
      roughness,
      metalness,
      reflectance,
      clearcoat,
      clearcoatRoughness,
      transmission,
      thickness,
      emissiveIntensity,
      materialKeyframes,
      setMaterialKeyframes,
      isAdvancedMaterialOpen,
      setIsAdvancedMaterialOpen,
      activeMaterialSettings,
      updateMaterialSetting,
      applyMaterialPreset,
    },
    light: {
      ambientColor,
      ambientIntensity,
      keyLightColor,
      setKeyLightColor,
      keyLightIntensity,
      setKeyLightIntensity,
      keyLightSoftness,
      setKeyLightSoftness,
      keyLightPositionKeyframes,
      setKeyLightPositionKeyframes,
      activeKeyLightPosition,
      lightPositionKeyframeAtPlayhead,
      toggleLightPositionKeyframeAtPlayhead,
      updateLightPositionXY,
      rimLightColor,
      rimLightIntensity,
    },
    selection: {
      inspectorRefs,
      selectedMotionTrackId,
      setSelectedMotionTrackId,
      selectTimelineTrack,
      selectTimelinePropertyRow,
    },
    timelineTracks: {
      tracks,
      setTracks,
      extrusionTrack,
      scaleTrack,
      lightingTrack,
    },
  } = editor

  const {
    sortedShapes,
    morph,
    selectedShapeFill,
    selectedShapeFillSecondary,
    selectedShapeGradientType,
    selectedShapeFillStops,
    iconAContent,
    iconBContent,
    colorA,
    renderColorASecondary,
    renderColorAStops,
    renderColorB,
    renderColorBSecondary,
    renderColorBStops,
    activeTransitionProgress,
    transitionType,
    wipeDirection,
    renderEnableGradient,
    renderGradientType,
    selectedShapeLayers,
    selectedLayerId,
    selectedLayerOverride,
    setSelectedLayerId,
    updateSelectedLayerScale,
    updateSelectedLayerDepth,
    toggleSelectedLayerVisibility,
    shapeNavigation,
    activeExtrusionDepth,
    activeRotationOffset,
    activeObjectScale,
    activeMoveOffset,
    activeKeyLightIntensity,
    activeGeometryQuality,
    activeInnerScale,
  } = useEditorRenderState({
    shapes,
    setShapes,
    selectedShapeId,
    setSelectedShapeId,
    currentTime,
    fillColor,
    fillColorSecondary,
    fillGradientType,
    fillStops,
    fillKeyframes,
    fillMode,
    enableGradient,
    extrusionTrack,
    scaleTrack,
    lightingTrack,
    extrusionDepth,
    rotationOffset,
    rotationAxisKeyframes,
    previewRotationY,
    objectScale,
    moveOffset,
    moveKeyframes,
    keyLightIntensity,
    geometryQuality,
    qualityKeyframes,
    innerElementScale,
    innerScaleKeyframes,
    markCustom,
  })

  const {
    handleDepthChange,
    handleRotationAxisChange,
    handleScaleChange,
    handleScaleAxisChange,
    handleViewRotationCommit,
    handleViewRotationSet,
    handleBrightnessChange,
    updateMoveAxis,
    updateQuality,
    resetView,
  } = useEditorMotionSurface({
    currentTime,
    duration,
    tracks,
    setTracks,
    setSelectedMotionTrackId,
    setActiveRecipeId,
    setExtrusionDepth,
    setRotationOffset,
    activeRotationOffset,
    rotationAxisKeyframes,
    setRotationAxisKeyframes,
    setPreviewRotationY,
    setObjectScale,
    setObjectScaleAxes,
    setIsScaleLocked,
    activeMoveOffset,
    setMoveOffset,
    setMoveKeyframes,
    setKeyLightIntensity,
    setGeometryQuality,
    setQualityKeyframes,
    geometryQuality,
    canvas3DRef,
  })

  const {
    openExport,
    uploadFileRef,
    handleUploadInputChange,
    handleDropSvg,
    triggerShapeUpload,
    exportModalProps,
  } = useEditorExportSurface({
    selectedShapeId,
    setShapes,
    canvasRef: canvas3DRef,
    exportTimelineVideo,
    materialPreset,
    colorA,
    colorB: renderColorB,
    roughness,
    metalness,
    reflectance,
    clearcoat,
    clearcoatRoughness,
    transmission,
    thickness,
    emissiveIntensity,
    extrusionDepth: activeExtrusionDepth,
    bevelEnabled,
    bevelThickness,
    bevelSize,
    bevelSegments,
    layerSpacing,
    ambientIntensity,
    keyLightIntensity: activeKeyLightIntensity,
    rimLightIntensity,
    svgPathA: iconAContent,
    svgPathB: iconBContent,
    markCustom,
  })

  const {
    timelineProps,
    previousBreakpoint,
    nextBreakpoint,
    atTimelineStart,
    atTimelineEnd,
    playbackProgress,
    goToPreviousBreakpoint,
    goToNextBreakpoint,
    goToEnd,
  } = useEditorTimelineSurface({
    currentTime,
    setCurrentTime,
    duration,
    setDuration,
    seekToTime,
    cancelAnimatedSeek,
    stopPlayback,
    isPlaying,
    isPreviewModelReady,
    loop,
    setLoop,
    tracks,
    setTracks,
    sortedShapes,
    shapes,
    setShapes,
    selectedShapeId,
    setSelectedShapeId,
    openShapePicker,
    setOpenShapePicker,
    selectedMotionTrackId,
    selectTimelineTrack,
    selectTimelinePropertyRow,
    fillKeyframes,
    setFillKeyframes,
    materialKeyframes,
    setMaterialKeyframes,
    keyLightPositionKeyframes,
    setKeyLightPositionKeyframes,
    rotationAxisKeyframes,
    setRotationAxisKeyframes,
    moveKeyframes,
    setMoveKeyframes,
    setQualityKeyframes,
    setInnerScaleKeyframes,
    selectedShapeFillStops,
    selectedShapeGradientType,
    activeMaterialSettings,
    activeKeyLightPosition,
    activeRotationOffset,
    activeMoveOffset,
    setShapeIcon,
    setShapeWipePair,
    addShapeAtPlayhead,
    removeShape,
    triggerShapeUpload,
    markCustom,
  })

  const { canvasProps, viewOptionsProps, playbackProps } =
    useEditorViewportSurface({
      iconAContent,
      iconBContent,
      materialPreset,
      colorA,
      colorB: renderColorB,
      colorASecondary: renderColorASecondary,
      colorBSecondary: renderColorBSecondary,
      colorAStops: renderColorAStops,
      colorBStops: renderColorBStops,
      enableGradient: renderEnableGradient,
      gradientType: renderGradientType,
      activeMaterialSettings,
      wireframe,
      extrusionDepth: activeExtrusionDepth,
      bevelEnabled,
      bevelThickness,
      bevelSize,
      bevelSegments,
      geometryQuality: activeGeometryQuality,
      layerSpacing,
      innerElementScale: activeInnerScale,
      transitionType,
      wipeDirection,
      transitionProgress: activeTransitionProgress,
      rotationOffset: activeRotationOffset,
      objectScale: activeObjectScale,
      objectScaleAxes,
      moveOffset: activeMoveOffset,
      isPlaying,
      ambientColor,
      ambientIntensity,
      keyLightColor,
      keyLightIntensity: activeKeyLightIntensity,
      keyLightPosition: activeKeyLightPosition,
      keyLightSoftness,
      rimLightColor,
      rimLightIntensity,
      zoom,
      viewInertiaEnabled,
      showCenterPoint,
      showTransformGizmo,
      selectedLayerId,
      pathOverridesA: morph.from.pathOverrides,
      pathOverridesB: morph.to.pathOverrides,
      playbackProgress,
      atTimelineStart,
      atTimelineEnd,
      hasPreviousBreakpoint: previousBreakpoint !== undefined,
      hasNextBreakpoint: nextBreakpoint !== undefined,
      zenMode,
      animatedSeekEnabled,
      setZoom,
      handleViewRotationCommit,
      handleViewRotationSet,
      handleScaleChange,
      handleScaleAxisChange,
      updateMoveAxis,
      handleRotationAxisChange,
      setIsPreviewModelReady,
      resetView,
      setViewInertiaEnabled,
      setShowCenterPoint,
      setShowTransformGizmo,
      setAnimatedSeekEnabled,
      handleReset,
      goToPreviousBreakpoint,
      handlePlayToggle,
      goToNextBreakpoint,
      goToEnd,
      setZenMode,
      markCustom,
    })

  const { styleProps, geometryProps, transformProps, lightProps } =
    useEditorInspectorSurface({
      currentTime,
      duration,
      setTracks,
      setSelectedMotionTrackId,
      setActiveRecipeId,
      fillKeyframes,
      setFillKeyframes,
      materialKeyframes,
      setMaterialKeyframes,
      selectedShapeFillStops,
      selectedShapeGradientType,
      activeMaterialSettings,
      scaleTrack,
      activeObjectScale,
      activeRotationOffset,
      rotationAxisKeyframes,
      setRotationAxisKeyframes,
      activeMoveOffset,
      moveKeyframes,
      setMoveKeyframes,
      keyLightPositionKeyframes,
      lightPositionKeyframeAtPlayhead,
      toggleLightPositionKeyframeAtPlayhead,
      markCustom,
      stopPlayback,
      setCurrentTime,
      fillRef: inspectorRefs.fill,
      materialRef: inspectorRefs.material,
      materialPreset,
      materialKeyframeCount: materialKeyframes.length,
      isAdvancedMaterialOpen,
      selectedShapeFill,
      selectedShapeFillSecondary,
      fillMode,
      onFillColorChange: updateFillColor,
      onGradientToggle: setGradientEnabled,
      onGradientTypeChange: updateGradientType,
      onStopsChange: updateFillStops,
      onMaterialPresetChange: applyMaterialPreset,
      onAdvancedMaterialOpenChange: setIsAdvancedMaterialOpen,
      onMaterialSettingChange: updateMaterialSetting,
      extrusionRef: inspectorRefs.extrusion,
      selectedMotionTrackId,
      extrusionTrack,
      activeExtrusionDepth,
      extrusionDepth,
      activeGeometryQuality,
      bevelEnabled,
      bevelSegments,
      onDepthChange: handleDepthChange,
      onBevelEnabledChange: setBevelEnabled,
      onBevelSegmentsChange: setBevelSegments,
      onQualityChange: updateQuality,
      onCustomEdit: markCustom,
      scaleRef: inspectorRefs.scale,
      rotationRef: inspectorRefs.rotation,
      moveRef: inspectorRefs.move,
      objectScale,
      objectScaleAxes,
      isScaleLocked,
      rotationOffset: activeRotationOffset,
      moveKeyframesLength: moveKeyframes.length,
      selectedShapeLayers,
      selectedLayerId,
      selectedLayerOverride,
      shapeNavigation,
      onScaleLockChange: setIsScaleLocked,
      onScaleChange: handleScaleChange,
      onScaleAxisChange: handleScaleAxisChange,
      onRotationAxisChange: handleRotationAxisChange,
      onMoveAxisChange: updateMoveAxis,
      onSelectLayer: setSelectedLayerId,
      onToggleLayerVisibility: toggleSelectedLayerVisibility,
      onLayerScaleChange: updateSelectedLayerScale,
      onLayerDepthChange: updateSelectedLayerDepth,
      lightingRef: inspectorRefs.lighting,
      lightingTrack,
      activeKeyLightIntensity,
      keyLightIntensity,
      activeKeyLightPosition,
      keyLightColor,
      keyLightSoftness,
      lightPositionIsKeyed: Boolean(lightPositionKeyframeAtPlayhead()),
      onLightPositionChange: updateLightPositionXY,
      onLightColorChange: setKeyLightColor,
      onLightSoftnessChange: setKeyLightSoftness,
      onToggleLightPositionKeyframe: toggleLightPositionKeyframeAtPlayhead,
      onBrightnessChange: handleBrightnessChange,
    })

  return {
    topBarProps: {
      zenMode,
      themeMounted,
      isLightTheme,
      themeToggleLabel,
      onZenModeChange: setZenMode,
      onThemeChange: setTheme,
      onExportOpen: openExport,
    },
    viewportProps: {
      zenMode,
      isDragging,
      onDragStateChange: setIsDragging,
      onDropSvg: handleDropSvg,
      canvasProps,
      viewOptionsProps,
      playbackProps,
    },
    inspectorProps: {
      zenMode,
      styleProps,
      geometryProps,
      transformProps,
      lightProps,
    },
    timelineProps: { zenMode, timelineProps },
    exportModalProps,
    uploadFileRef,
    canvas3DRef,
    onUploadInputChange: handleUploadInputChange,
  }
}
