"use client"

import { useMemo } from "react"
import type { ExportSceneSnapshot } from "./ExportSceneSnapshot"

export function useExportSceneSnapshot({
  materialPreset,
  colorA,
  colorB,
  roughness,
  metalness,
  reflectance,
  clearcoat,
  clearcoatRoughness,
  transmission,
  thickness,
  emissiveIntensity,
  extrusionDepth,
  bevelEnabled,
  bevelThickness,
  bevelSize,
  bevelSegments,
  layerSpacing,
  ambientIntensity,
  keyLightIntensity,
  rimLightIntensity,
  svgPathA,
  svgPathB,
}: ExportSceneSnapshot): ExportSceneSnapshot {
  return useMemo(
    () => ({
      materialPreset,
      colorA,
      colorB,
      roughness,
      metalness,
      reflectance,
      clearcoat,
      clearcoatRoughness,
      transmission,
      thickness,
      emissiveIntensity,
      extrusionDepth,
      bevelEnabled,
      bevelThickness,
      bevelSize,
      bevelSegments,
      layerSpacing,
      ambientIntensity,
      keyLightIntensity,
      rimLightIntensity,
      svgPathA,
      svgPathB,
    }),
    [
      materialPreset,
      colorA,
      colorB,
      roughness,
      metalness,
      reflectance,
      clearcoat,
      clearcoatRoughness,
      transmission,
      thickness,
      emissiveIntensity,
      extrusionDepth,
      bevelEnabled,
      bevelThickness,
      bevelSize,
      bevelSegments,
      layerSpacing,
      ambientIntensity,
      keyLightIntensity,
      rimLightIntensity,
      svgPathA,
      svgPathB,
    ]
  )
}
