"use client"

import { isInspectorInputDragActive } from "./InspectorControlModel"
import type { EditorBaseState } from "./useEditorBaseState"
import { useEditorHistorySurface } from "./useEditorHistorySurface"
import { useEditorRecipeSurface } from "./useEditorRecipeSurface"

export function useEditorDocumentLifecycle(editor: EditorBaseState) {
  const {
    playback,
    shapes,
    geometry,
    transform,
    fill,
    material,
    light,
    selection,
    timelineTracks,
  } = editor

  useEditorRecipeSurface({
    duration: playback.duration,
    setActiveRecipeId: shapes.setActiveRecipeId,
    setMaterialPreset: material.setMaterialPreset,
    applyRecipeFill: fill.applyRecipeFill,
    setShapes: shapes.setShapes,
    setSelectedShapeId: shapes.setSelectedShapeId,
    setMaterialBaseSettings: material.setMaterialBaseSettings,
    setGeometryBaseSettings: geometry.setGeometryBaseSettings,
    setTransformBaseSettings: transform.setTransformBaseSettings,
    setRotationAxisKeyframes: transform.setRotationAxisKeyframes,
    setMoveKeyframes: transform.setMoveKeyframes,
    setQualityKeyframes: geometry.setQualityKeyframes,
    setInnerScaleKeyframes: geometry.setInnerScaleKeyframes,
    setLightBaseSettings: light.setLightBaseSettings,
    setKeyLightPositionKeyframes: light.setKeyLightPositionKeyframes,
    setTracks: timelineTracks.setTracks,
    setSelectedMotionTrackId: selection.setSelectedMotionTrackId,
    setCurrentTime: playback.setCurrentTime,
    setIsPlaying: playback.setIsPlaying,
  })

  useEditorHistorySurface({
    activeRecipeId: shapes.activeRecipeId,
    setActiveRecipeId: shapes.setActiveRecipeId,
    shapes: shapes.shapes,
    setShapes: shapes.setShapes,
    setSelectedShapeId: shapes.setSelectedShapeId,
    setOpenShapePicker: shapes.setOpenShapePicker,
    duration: playback.duration,
    setDuration: playback.setDuration,
    setCurrentTime: playback.setCurrentTime,
    materialPreset: material.materialPreset,
    setMaterialPreset: material.setMaterialPreset,
    materialSettings: material.baseMaterialSettings,
    materialKeyframes: material.materialKeyframes,
    setMaterialKeyframes: material.setMaterialKeyframes,
    setMaterialBaseSettings: material.setMaterialBaseSettings,
    extrusionDepth: geometry.extrusionDepth,
    bevelEnabled: geometry.bevelEnabled,
    bevelThickness: geometry.bevelThickness,
    bevelSize: geometry.bevelSize,
    bevelSegments: geometry.bevelSegments,
    geometryQuality: geometry.geometryQuality,
    qualityKeyframes: geometry.qualityKeyframes,
    setQualityKeyframes: geometry.setQualityKeyframes,
    layerSpacing: geometry.layerSpacing,
    innerElementScale: geometry.innerElementScale,
    setGeometryBaseSettings: geometry.setGeometryBaseSettings,
    innerScaleKeyframes: geometry.innerScaleKeyframes,
    setInnerScaleKeyframes: geometry.setInnerScaleKeyframes,
    objectScale: transform.objectScale,
    objectScaleAxes: transform.objectScaleAxes,
    moveOffset: transform.moveOffset,
    setTransformBaseSettings: transform.setTransformBaseSettings,
    moveKeyframes: transform.moveKeyframes,
    setMoveKeyframes: transform.setMoveKeyframes,
    enableGradient: fill.enableGradient,
    fillMode: fill.fillMode,
    fillColor: fill.fillColor,
    fillColorSecondary: fill.fillColorSecondary,
    fillGradientType: fill.fillGradientType,
    fillStops: fill.fillStops,
    fillKeyframes: fill.fillKeyframes,
    restoreFillState: fill.restoreFillState,
    rotationOffset: transform.rotationOffset,
    rotationAxisKeyframes: transform.rotationAxisKeyframes,
    setRotationAxisKeyframes: transform.setRotationAxisKeyframes,
    keyLightColor: light.keyLightColor,
    keyLightIntensity: light.keyLightIntensity,
    keyLightPosition: light.keyLightPosition,
    keyLightSoftness: light.keyLightSoftness,
    setLightBaseSettings: light.setLightBaseSettings,
    keyLightPositionKeyframes: light.keyLightPositionKeyframes,
    setKeyLightPositionKeyframes: light.setKeyLightPositionKeyframes,
    tracks: timelineTracks.tracks,
    setTracks: timelineTracks.setTracks,
    setIsPlaying: playback.setIsPlaying,
    isInputDragActive: isInspectorInputDragActive,
    onPlayPause: playback.togglePlayback,
  })
}
