"use client"

import { useMemo } from "react"
import type { SidebarTransformProps } from "./InspectorSidebar"
import type { TransformSidebarPropsArgs } from "./InspectorSidebarPropsModel"

export function useTransformSidebarProps({
  scaleRef,
  rotationRef,
  moveRef,
  selectedMotionTrackId,
  scaleTrack,
  activeObjectScale,
  objectScale,
  objectScaleAxes,
  isScaleLocked,
  rotationOffset,
  rotationAxisKeyframes,
  moveKeyframesLength,
  activeMoveOffset,
  selectedShapeLayers,
  selectedLayer,
  selectedLayerId,
  selectedLayerOverride,
  shapeNavigation,
  transformKeyframeControl,
  setSelectedMotionTrackId,
  onScaleLockChange,
  onScaleChange,
  onScaleAxisChange,
  onRotationAxisChange,
  onMoveAxisChange,
  onSelectLayer,
  onToggleLayerVisibility,
  onLayerScaleChange,
  onLayerDepthChange,
  onCustomEdit,
}: TransformSidebarPropsArgs) {
  return useMemo<SidebarTransformProps>(
    () => ({
      scaleRef,
      rotationRef,
      moveRef,
      activeTrackId: selectedMotionTrackId,
      scaleTrack,
      activeObjectScale,
      objectScale,
      objectScaleAxes,
      isScaleLocked,
      rotationOffset,
      rotationAxisKeyframes,
      moveKeyframesLength,
      activeMoveOffset,
      selectedShapeLayers,
      selectedLayer,
      selectedLayerId,
      selectedLayerOverride,
      shapeNavigation,
      transformKeyframeControl,
      onActivateTrack: setSelectedMotionTrackId,
      onScaleLockChange,
      onScaleChange,
      onScaleAxisChange,
      onRotationAxisChange,
      onMoveAxisChange,
      onSelectLayer,
      onToggleLayerVisibility,
      onLayerScaleChange,
      onLayerDepthChange,
      onCustomEdit,
    }),
    [
      scaleRef,
      rotationRef,
      moveRef,
      selectedMotionTrackId,
      scaleTrack,
      activeObjectScale,
      objectScale,
      objectScaleAxes,
      isScaleLocked,
      rotationOffset,
      rotationAxisKeyframes,
      moveKeyframesLength,
      activeMoveOffset,
      selectedShapeLayers,
      selectedLayer,
      selectedLayerId,
      selectedLayerOverride,
      shapeNavigation,
      transformKeyframeControl,
      setSelectedMotionTrackId,
      onScaleLockChange,
      onScaleChange,
      onScaleAxisChange,
      onRotationAxisChange,
      onMoveAxisChange,
      onSelectLayer,
      onToggleLayerVisibility,
      onLayerScaleChange,
      onLayerDepthChange,
      onCustomEdit,
    ]
  )
}
